apiVersion: apps/v1
kind: Deployment

metadata:
  name: my-nginx-deployment
spec:
  replicas: 3
  selector:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"  
              cpu: "250m"     
            limits:
              memory: "128Mi"  
              cpu: "500m"      
          livenessProbe:
            httpGet:
              path: /healthz  
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readiness  
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
